export { default as Header } from './header'
export { default as Destinations } from './destinations'
export { default as NextTrip } from './nextTrip'
export { default as Button } from './button'
export { default as BookSeat } from './bookSeat'